"""Service layer for the generated project."""
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from .models import Tracker, TrackerCreate, TrackerUpdate
from .store import store

app = FastAPI(
    title="Tutorial Manufacturing Shortage Tracker API",
    version="0.1.0",
    description="REST API for Tutorial Manufacturing Shortage Tracker. Generated by the Agentic SDLC workflow.",
    docs_url="/docs",
    openapi_url="/openapi.json",
    openapi_tags=[
        {"name": "health", "description": "Liveness probe used by the deploy pipeline."},
        {"name": "trackers", "description": "Trackers managed by this service."},
    ],
)

# The UI is a separate App Service, so it is a cross-origin caller.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", tags=["health"])
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/trackers", response_model=List[Tracker], tags=["trackers"])
def list_items(status: Optional[str] = Query(default=None)) -> List[dict]:
    return store.list(status)


@app.post("/api/trackers", response_model=Tracker, status_code=201, tags=["trackers"])
def create_item(body: TrackerCreate) -> dict:
    return store.create(body.model_dump())


@app.get("/api/trackers/{item_id}", response_model=Tracker, tags=["trackers"])
def get_item(item_id: int) -> dict:
    item = store.get(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Tracker not found")
    return item


@app.patch("/api/trackers/{item_id}", response_model=Tracker, tags=["trackers"])
def update_item(item_id: int, body: TrackerUpdate) -> dict:
    item = store.update(item_id, body.model_dump())
    if item is None:
        raise HTTPException(status_code=404, detail="Tracker not found")
    return item


@app.delete("/api/trackers/{item_id}", status_code=204, tags=["trackers"])
def delete_item(item_id: int) -> None:
    if not store.delete(item_id):
        raise HTTPException(status_code=404, detail="Tracker not found")
